---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: package-lock.json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: backend:check
        name: backend:check
        entry: task backend:check
        language: system
        files: backend
        pass_filenames: false
      - id: frontend:check
        name: frontend:check
        entry: task frontend:check
        language: system
        files: frontend
        pass_filenames: false
...
