---
version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: couplet
      POSTGRES_USER: ${DB_USER:?database username not specified}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?database password not specified}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: backend.dockerfile
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER:?database username not specified}
      DB_PASSWORD: ${DB_PASSWORD:?database password not specified}
      DB_NAME: couplet
    ports:
      - ${PORT:-8080}:${PORT:-8080}
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: ./openapi.yaml
    ports:
      - 80:8080
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
volumes:
  postgres-data:
...
