---
version: '3'

tasks:
  run:
    deps:
      - build
    summary: Runs the backend server
    cmds:
      - ./server
  build:
    deps:
      - generate
    summary: Build backend executables
    sources:
      - ./**/*.go
    generates:
      - server
      - data-gen
    cmds:
      - go mod download
      - go build ./cmd/server
      - go build ./cmd/data-gen
  generate:
    aliases:
      - gen
    summary: Generate server code from OpenAPI spec
    sources:
      - ../openapi.yaml
    generates:
      - internal/api/**
    cmds:
      - go generate ./...
  clean:
    summary: Delete build files
    cmds:
      - rm -f server
      - rm -f data-gen
      - rm -rf internal/api
  test:
    deps:
      - generate
    summary: Run backend tests
    cmds:
      - go test ./...
  check:
    deps:
      - generate
    summary: Run static analysis checks
    cmds:
      - golangci-lint run ./...
      - go mod tidy
      - go fmt ./...
      - go vet ./...
...
